{{- $data := dict }}
{{- $secrets := .Values.secrets }}
{{- if and (not .Values.postgresql.internal.enabled) $secrets.database.dsn.value (not $secrets.database.dsn.existingSecret) }}
{{- $_ := set $data $secrets.database.dsn.existingSecretKey $secrets.database.dsn.value }}
{{- end }}
{{- if and $secrets.redis.password.value (not $secrets.redis.password.existingSecret) }}
{{- $_ := set $data $secrets.redis.password.existingSecretKey $secrets.redis.password.value }}
{{- end }}
{{- if and $secrets.memgraph.username.value (not $secrets.memgraph.username.existingSecret) }}
{{- $_ := set $data $secrets.memgraph.username.existingSecretKey $secrets.memgraph.username.value }}
{{- end }}
{{- if and $secrets.memgraph.password.value (not $secrets.memgraph.password.existingSecret) }}
{{- $_ := set $data $secrets.memgraph.password.existingSecretKey $secrets.memgraph.password.value }}
{{- end }}
{{- if and $secrets.profiling.username.value (not $secrets.profiling.username.existingSecret) }}
{{- $_ := set $data $secrets.profiling.username.existingSecretKey $secrets.profiling.username.value }}
{{- end }}
{{- if and $secrets.profiling.password.value (not $secrets.profiling.password.existingSecret) }}
{{- $_ := set $data $secrets.profiling.password.existingSecretKey $secrets.profiling.password.value }}
{{- end }}
{{- if and $secrets.profiling.authToken.value (not $secrets.profiling.authToken.existingSecret) }}
{{- $_ := set $data $secrets.profiling.authToken.existingSecretKey $secrets.profiling.authToken.value }}
{{- end }}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oecs-hub.secretName" . }}
  labels:
    {{- include "oecs-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := $data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
