apiVersion: v1
kind: Service
metadata:
  name: {{ include "oecs-hub.fullname" . }}
  labels:
    {{- include "oecs-hub.labels" . | nindent 4 }}
  {{- with .Values.grpc.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grpc.service.type }}
  ports:
    - port: {{ .Values.grpc.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "oecs-hub.selectorLabels" . | nindent 4 }}
